FROM docker.io/python:3.10.15-slim-bookworm

WORKDIR /workdir

EXPOSE 8000

RUN apt update

RUN apt install wget curl libpq-dev libgl1 libglib2.0-0 -y 

COPY ./requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./debian_setup.bash .

RUN debian_setup.bash

COPY . .

ENTRYPOINT ["fastapi","run","main.py"]
