name: Docker Dev Image CI

on:
  push:
    branches: ["main", "stable", "non_stable"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USRNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: giangltce/culcon_admin_backend
          tags: |
            type=raw,value=dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: giangltce/culcon_admin_backend:dev
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha, mode=max
          file: Dockerfile-Dev

  deploy-branch:
    name: Push to Deploy Branch
    needs: build
    runs-on: ubuntu-latest
    # Only run on push to main/stable/non_stable branches, not on PRs
    if: github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history for branch operations

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Push to deploy branch
        run: |
          # Determine target deploy branch based on source branch
          DEPLOY_BRANCH="deploy"

          # Create or update the deploy branch
          git checkout $DEPLOY_BRANCH
          git merge main
          git push origin $DEPLOY_BRANCH
